export const LOADED = 'TODOS/LOADED';
export const ADDED = 'TODOS/ADDED';
export const TOGGLED = 'TODOS/TOGGLED';
export const COLORSELECTED = 'TODOS/COLORSELECTED';
export const DELETED = 'TODOS/DELETED';
export const ALL_COMPLETED = 'TODOS/ALL_COMPLETED';
export const CLEAR_COMPLETED = 'TODOS/CLEAR_COMPLETED';
